### ISSUE TITLE
Feedback for “Introduction”

### ISSUE THREAD

**Issue by mayanknav** [cosmostation/cosmostation-docs#34]
I am not able to get the api key. Also after getting the API key would I be able to get the correct data from the APIs as it is still on beta. Please confirm.

**Comment by jeongeunlee1209** [comment]
Hello, thank you for getting interest in the public API service provided by the Cosmostation team.

Yes. you would be getting the correct data from the API although the service is still in the beta phase.
If you would like to know the types of query that you are able to use and the chains that you are able to use, then please refer to the API documentation link here (https://docs.cosmostation.io/apis)

In order for users to get the API keys for the public API service, then please follow the steps.

1. Download the Cosmostation extension wallet
https://chrome.google.com/webstore/detail/cosmostation-wallet/fpkhgmpbidmiogeglndfbkegfdlnajnf

2. Please follow the steps of creating an account if you do not have one. You can follow 'Restore wallet with a mnemonic phrase' if you already have an existing account
https://docs.cosmostation.io/extension/guide/account/add-account

3. Go to api.mintscan.io and click on Build now

4. Click on the Sign up -> enter the email address that you received the whitelist email -> Click on the Sign up button
Then you should be able to get a verification email

5. Go to your email and click on the 'verify Email'
Then it will lead you to the api.mintscan.io again

6. Click on the Build now -> enter the Email again and click on the Sign in

Your Cosmos wallet and your email address will be paired 1:1 which means that you should be using the same Cosmos wallet for your email address. When you successfully sign into the http://api.mintscan.io/, please create an API key and then provide us with the screenshot of the dashboard of the API service with your email address that you used to sign in. Please send us an email to api@cosmostation.io.

If you need any support for getting the data, please go to the documentation link below
https://docs.cosmostation.io/apis

Will be waiting for your email so that we are able to approve the API key that you created. Thank you if you have further questions, please send us an email to api@cosmostation.io. We will be closing the current issue.
